DROP TABLE IF EXISTS pwdRecover;
CREATE TABLE pwdRecover
(
    `id`          INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `recoverLink` VARCHAR(255) NOT NULL,
    `userId`      INT(11) UNSIGNED,
    `created`     TIMESTAMP,
    `modified`    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TRIGGER pwdRecover_insert BEFORE INSERT ON `pwdRecover` FOR EACH ROW SET NEW.created = CURRENT_TIMESTAMP;
